/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "KPIMonitoringModule"
 * 	found in "KPIMonitoring.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_CuCpResourceStatusReport_H_
#define	_CuCpResourceStatusReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <BIT_STRING.h>
#include "CuCpResourceStatus.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CuCpResourceStatusReport */
typedef struct CuCpResourceStatusReport {
	PrintableString_t	*cuCpName	/* OPTIONAL */;
	BIT_STRING_t	 gnbId;
	CuCpResourceStatus_t	 cuCpResourceStatus;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CuCpResourceStatusReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CuCpResourceStatusReport;

#ifdef __cplusplus
}
#endif

#endif	/* _CuCpResourceStatusReport_H_ */
#include <asn_internal.h>
