/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-modified-15-05.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_MobilityParametersInformation_H_
#define	_MobilityParametersInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MobilityParametersInformation */
typedef struct MobilityParametersInformation {
	long	 handoverTriggerChange;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MobilityParametersInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MobilityParametersInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _MobilityParametersInformation_H_ */
#include <asn_internal.h>
