/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-modified-15-05.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_ServiceType_H_
#define	_ServiceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceType {
	ServiceType_qMC_for_streaming_service	= 0,
	ServiceType_qMC_for_MTSI_service	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ServiceType;

/* ServiceType */
typedef long	 ServiceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceType;
asn_struct_free_f ServiceType_free;
asn_struct_print_f ServiceType_print;
asn_constr_check_f ServiceType_constraint;
ber_type_decoder_f ServiceType_decode_ber;
der_type_encoder_f ServiceType_encode_der;
xer_type_decoder_f ServiceType_decode_xer;
xer_type_encoder_f ServiceType_encode_xer;
per_type_decoder_f ServiceType_decode_uper;
per_type_encoder_f ServiceType_encode_uper;
per_type_decoder_f ServiceType_decode_aper;
per_type_encoder_f ServiceType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceType_H_ */
#include <asn_internal.h>
