/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-modified-15-05.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_UE_RLF_Report_Container_for_extended_bands_H_
#define	_UE_RLF_Report_Container_for_extended_bands_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UE-RLF-Report-Container-for-extended-bands */
typedef OCTET_STRING_t	 UE_RLF_Report_Container_for_extended_bands_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_RLF_Report_Container_for_extended_bands;
asn_struct_free_f UE_RLF_Report_Container_for_extended_bands_free;
asn_struct_print_f UE_RLF_Report_Container_for_extended_bands_print;
asn_constr_check_f UE_RLF_Report_Container_for_extended_bands_constraint;
ber_type_decoder_f UE_RLF_Report_Container_for_extended_bands_decode_ber;
der_type_encoder_f UE_RLF_Report_Container_for_extended_bands_encode_der;
xer_type_decoder_f UE_RLF_Report_Container_for_extended_bands_decode_xer;
xer_type_encoder_f UE_RLF_Report_Container_for_extended_bands_encode_xer;
per_type_decoder_f UE_RLF_Report_Container_for_extended_bands_decode_uper;
per_type_encoder_f UE_RLF_Report_Container_for_extended_bands_encode_uper;
per_type_decoder_f UE_RLF_Report_Container_for_extended_bands_decode_aper;
per_type_encoder_f UE_RLF_Report_Container_for_extended_bands_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_RLF_Report_Container_for_extended_bands_H_ */
#include <asn_internal.h>
