/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Descriptions"
 * 	found in "../../asn_defs/asn1/x2ap-modified-15-05.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#include "X2SuccessfulOutcome.h"

static const long asn_VAL_1_id_handoverPreparation = 0;
static const long asn_VAL_1_reject = 0;
static const long asn_VAL_2_id_reset = 7;
static const long asn_VAL_2_reject = 0;
static const long asn_VAL_3_id_x2Setup = 6;
static const long asn_VAL_3_reject = 0;
static const long asn_VAL_4_id_resourceStatusReportingInitiation = 9;
static const long asn_VAL_4_reject = 0;
static const long asn_VAL_5_id_eNBConfigurationUpdate = 8;
static const long asn_VAL_5_reject = 0;
static const long asn_VAL_6_id_mobilitySettingsChange = 12;
static const long asn_VAL_6_reject = 0;
static const long asn_VAL_7_id_cellActivation = 15;
static const long asn_VAL_7_reject = 0;
static const long asn_VAL_8_id_seNBAdditionPreparation = 19;
static const long asn_VAL_8_reject = 0;
static const long asn_VAL_9_id_meNBinitiatedSeNBModificationPreparation = 21;
static const long asn_VAL_9_reject = 0;
static const long asn_VAL_10_id_seNBinitiatedSeNBModification = 22;
static const long asn_VAL_10_reject = 0;
static const long asn_VAL_11_id_seNBinitiatedSeNBRelease = 24;
static const long asn_VAL_11_reject = 0;
static const long asn_VAL_12_id_x2Removal = 18;
static const long asn_VAL_12_reject = 0;
static const long asn_VAL_13_id_retrieveUEContext = 26;
static const long asn_VAL_13_reject = 0;
static const long asn_VAL_14_id_sgNBAdditionPreparation = 27;
static const long asn_VAL_14_reject = 0;
static const long asn_VAL_15_id_meNBinitiatedSgNBModificationPreparation = 29;
static const long asn_VAL_15_reject = 0;
static const long asn_VAL_16_id_sgNBinitiatedSgNBModification = 30;
static const long asn_VAL_16_reject = 0;
static const long asn_VAL_17_id_meNBinitiatedSgNBRelease = 31;
static const long asn_VAL_17_ignore = 1;
static const long asn_VAL_18_id_sgNBinitiatedSgNBRelease = 32;
static const long asn_VAL_18_reject = 0;
static const long asn_VAL_19_id_sgNBChange = 34;
static const long asn_VAL_19_reject = 0;
static const long asn_VAL_20_id_endcX2Setup = 36;
static const long asn_VAL_20_reject = 0;
static const long asn_VAL_21_id_endcConfigurationUpdate = 37;
static const long asn_VAL_21_reject = 0;
static const long asn_VAL_22_id_endcCellActivation = 39;
static const long asn_VAL_22_reject = 0;
static const long asn_VAL_23_id_endcPartialReset = 40;
static const long asn_VAL_23_reject = 0;
static const long asn_VAL_24_id_eUTRANRCellResourceCoordination = 41;
static const long asn_VAL_24_reject = 0;
static const long asn_VAL_25_id_endcX2Removal = 43;
static const long asn_VAL_25_reject = 0;
static const long asn_VAL_26_id_snStatusTransfer = 4;
static const long asn_VAL_26_ignore = 1;
static const long asn_VAL_27_id_uEContextRelease = 5;
static const long asn_VAL_27_ignore = 1;
static const long asn_VAL_28_id_handoverCancel = 1;
static const long asn_VAL_28_ignore = 1;
static const long asn_VAL_29_id_errorIndication = 3;
static const long asn_VAL_29_ignore = 1;
static const long asn_VAL_30_id_resourceStatusReporting = 10;
static const long asn_VAL_30_ignore = 1;
static const long asn_VAL_31_id_loadIndication = 2;
static const long asn_VAL_31_ignore = 1;
static const long asn_VAL_32_id_privateMessage = 11;
static const long asn_VAL_32_ignore = 1;
static const long asn_VAL_33_id_rLFIndication = 13;
static const long asn_VAL_33_ignore = 1;
static const long asn_VAL_34_id_handoverReport = 14;
static const long asn_VAL_34_ignore = 1;
static const long asn_VAL_35_id_x2Release = 16;
static const long asn_VAL_35_reject = 0;
static const long asn_VAL_36_id_x2APMessageTransfer = 17;
static const long asn_VAL_36_reject = 0;
static const long asn_VAL_37_id_seNBReconfigurationCompletion = 20;
static const long asn_VAL_37_ignore = 1;
static const long asn_VAL_38_id_meNBinitiatedSeNBRelease = 23;
static const long asn_VAL_38_ignore = 1;
static const long asn_VAL_39_id_seNBCounterCheck = 25;
static const long asn_VAL_39_reject = 0;
static const long asn_VAL_40_id_sgNBReconfigurationCompletion = 28;
static const long asn_VAL_40_ignore = 1;
static const long asn_VAL_41_id_sgNBCounterCheck = 33;
static const long asn_VAL_41_reject = 0;
static const long asn_VAL_42_id_rRCTransfer = 35;
static const long asn_VAL_42_reject = 0;
static const long asn_VAL_43_id_secondaryRATDataUsageReport = 38;
static const long asn_VAL_43_reject = 0;
static const long asn_VAL_44_id_SgNBActivityNotification = 42;
static const long asn_VAL_44_reject = 0;
static const long asn_VAL_45_id_dataForwardingAddressIndication = 44;
static const long asn_VAL_45_ignore = 1;
static const long asn_VAL_46_id_gNBStatusIndication = 45;
static const long asn_VAL_46_ignore = 1;
static const asn_ioc_cell_t asn_IOS_X2AP_ELEMENTARY_PROCEDURES_1_rows[] = {
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_HandoverRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_HandoverRequestAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_HandoverPreparationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_1_id_handoverPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_1_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ResetRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_ResetResponse },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_2_id_reset },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_2_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_X2SetupRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_X2SetupResponse },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_X2SetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_3_id_x2Setup },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_3_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ResourceStatusRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_ResourceStatusResponse },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_ResourceStatusFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_4_id_resourceStatusReportingInitiation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_4_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ENBConfigurationUpdate },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_ENBConfigurationUpdateAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_ENBConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_5_id_eNBConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_5_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_MobilityChangeRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_MobilityChangeAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_MobilityChangeFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_6_id_mobilitySettingsChange },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_6_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_CellActivationRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_CellActivationResponse },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_CellActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_7_id_cellActivation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_7_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SeNBAdditionRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SeNBAdditionRequestAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_SeNBAdditionRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_8_id_seNBAdditionPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_8_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SeNBModificationRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SeNBModificationRequestAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_SeNBModificationRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_9_id_meNBinitiatedSeNBModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_9_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SeNBModificationRequired },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SeNBModificationConfirm },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_SeNBModificationRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_10_id_seNBinitiatedSeNBModification },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_10_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SeNBReleaseRequired },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SeNBReleaseConfirm },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_11_id_seNBinitiatedSeNBRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_11_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_X2RemovalRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_X2RemovalResponse },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_X2RemovalFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_12_id_x2Removal },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_12_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_RetrieveUEContextRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_RetrieveUEContextResponse },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_RetrieveUEContextFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_13_id_retrieveUEContext },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_13_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBAdditionRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SgNBAdditionRequestAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_SgNBAdditionRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_14_id_sgNBAdditionPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_14_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBModificationRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SgNBModificationRequestAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_SgNBModificationRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_15_id_meNBinitiatedSgNBModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_15_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBModificationRequired },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SgNBModificationConfirm },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_SgNBModificationRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_16_id_sgNBinitiatedSgNBModification },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_16_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBReleaseRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SgNBReleaseRequestAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_SgNBReleaseRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_17_id_meNBinitiatedSgNBRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_17_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBReleaseRequired },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SgNBReleaseConfirm },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_18_id_sgNBinitiatedSgNBRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_18_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBChangeRequired },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_SgNBChangeConfirm },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_SgNBChangeRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_19_id_sgNBChange },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_19_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ENDCX2SetupRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_ENDCX2SetupResponse },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_ENDCX2SetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_20_id_endcX2Setup },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_20_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ENDCConfigurationUpdate },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_ENDCConfigurationUpdateAcknowledge },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_ENDCConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_21_id_endcConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_21_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ENDCCellActivationRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_ENDCCellActivationResponse },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_ENDCCellActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_22_id_endcCellActivation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_22_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ENDCPartialResetRequired },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_ENDCPartialResetConfirm },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_23_id_endcPartialReset },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_23_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_EUTRANRCellResourceCoordinationRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_EUTRANRCellResourceCoordinationResponse },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_24_id_eUTRANRCellResourceCoordination },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_24_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ENDCX2RemovalRequest },
	{ "&X2SuccessfulOutcome", aioc__type, &asn_DEF_ENDCX2RemovalResponse },
	{ "&X2UnsuccessfulOutcome", aioc__type, &asn_DEF_ENDCX2RemovalFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_25_id_endcX2Removal },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_25_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SNStatusTransfer },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_26_id_snStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_26_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_UEContextRelease },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_27_id_uEContextRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_27_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_HandoverCancel },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_28_id_handoverCancel },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_28_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ErrorIndication },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_29_id_errorIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_29_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_ResourceStatusUpdate },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_30_id_resourceStatusReporting },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_30_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_LoadInformation },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_31_id_loadIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_31_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_PrivateMessage },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_32_id_privateMessage },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_32_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_RLFIndication },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_33_id_rLFIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_33_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_HandoverReport },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_34_id_handoverReport },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_34_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_X2Release },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_35_id_x2Release },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_35_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_X2APMessageTransfer },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_36_id_x2APMessageTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_36_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SeNBReconfigurationComplete },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_37_id_seNBReconfigurationCompletion },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_37_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SeNBReleaseRequest },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_38_id_meNBinitiatedSeNBRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_38_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SeNBCounterCheckRequest },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_39_id_seNBCounterCheck },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_39_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBReconfigurationComplete },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_40_id_sgNBReconfigurationCompletion },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_40_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBCounterCheckRequest },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_41_id_sgNBCounterCheck },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_41_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_RRCTransfer },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_42_id_rRCTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_42_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SecondaryRATDataUsageReport },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_43_id_secondaryRATDataUsageReport },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_43_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_SgNBActivityNotification },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_44_id_SgNBActivityNotification },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_44_reject },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_DataForwardingAddressIndication },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_45_id_dataForwardingAddressIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_45_ignore },
	{ "&X2InitiatingMessage", aioc__type, &asn_DEF_GNBStatusIndication },
	{ "&X2SuccessfulOutcome",  },
	{ "&X2UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_46_id_gNBStatusIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_46_ignore }
};
static const asn_ioc_set_t asn_IOS_X2AP_ELEMENTARY_PROCEDURES_1[] = {
	{ 46, 5, asn_IOS_X2AP_ELEMENTARY_PROCEDURES_1_rows }
};
static int
memb_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_X2SuccessfulOutcome_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_X2AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct X2SuccessfulOutcome, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_X2SuccessfulOutcome_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_X2AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 1; /* &X2SuccessfulOutcome */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct X2SuccessfulOutcome, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_per_constraints_t asn_PER_memb_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_value_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.HandoverRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HandoverRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.ResetResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResetResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResetResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.X2SetupResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2SetupResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"X2SetupResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.ResourceStatusResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResourceStatusResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResourceStatusResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.ENBConfigurationUpdateAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ENBConfigurationUpdateAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENBConfigurationUpdateAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.MobilityChangeAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MobilityChangeAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"MobilityChangeAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.CellActivationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_CellActivationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CellActivationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SeNBAdditionRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SeNBAdditionRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBAdditionRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SeNBModificationRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SeNBModificationRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBModificationRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SeNBModificationConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SeNBModificationConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBModificationConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SeNBReleaseConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SeNBReleaseConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBReleaseConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.X2RemovalResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2RemovalResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"X2RemovalResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.RetrieveUEContextResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RetrieveUEContextResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RetrieveUEContextResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SgNBAdditionRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SgNBAdditionRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBAdditionRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SgNBModificationRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SgNBModificationRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBModificationRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SgNBModificationConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SgNBModificationConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBModificationConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SgNBReleaseRequestAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SgNBReleaseRequestAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBReleaseRequestAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SgNBReleaseConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SgNBReleaseConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBReleaseConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.SgNBChangeConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SgNBChangeConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBChangeConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.ENDCX2SetupResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ENDCX2SetupResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCX2SetupResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.ENDCConfigurationUpdateAcknowledge),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ENDCConfigurationUpdateAcknowledge,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCConfigurationUpdateAcknowledge"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.ENDCCellActivationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ENDCCellActivationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCCellActivationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.ENDCPartialResetConfirm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ENDCPartialResetConfirm,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCPartialResetConfirm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.EUTRANRCellResourceCoordinationResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EUTRANRCellResourceCoordinationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"EUTRANRCellResourceCoordinationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome__value, choice.ENDCX2RemovalResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ENDCX2RemovalResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCX2RemovalResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 24 }, /* HandoverRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 23 }, /* ResetResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 22 }, /* X2SetupResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 21 }, /* ResourceStatusResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 20 }, /* ENBConfigurationUpdateAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 19 }, /* MobilityChangeAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -6, 18 }, /* CellActivationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -7, 17 }, /* SeNBAdditionRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -8, 16 }, /* SeNBModificationRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -9, 15 }, /* SeNBModificationConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -10, 14 }, /* SeNBReleaseConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -11, 13 }, /* X2RemovalResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -12, 12 }, /* RetrieveUEContextResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -13, 11 }, /* SgNBAdditionRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -14, 10 }, /* SgNBModificationRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -15, 9 }, /* SgNBModificationConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 16, -16, 8 }, /* SgNBReleaseRequestAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 17, -17, 7 }, /* SgNBReleaseConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 18, -18, 6 }, /* SgNBChangeConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 19, -19, 5 }, /* ENDCX2SetupResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 20, -20, 4 }, /* ENDCConfigurationUpdateAcknowledge */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 21, -21, 3 }, /* ENDCCellActivationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 22, -22, 2 }, /* ENDCPartialResetConfirm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 23, -23, 1 }, /* EUTRANRCellResourceCoordinationResponse */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 24, -24, 0 } /* ENDCX2RemovalResponse */
};
static asn_CHOICE_specifics_t asn_SPC_value_specs_4 = {
	sizeof(struct X2SuccessfulOutcome__value),
	offsetof(struct X2SuccessfulOutcome__value, _asn_ctx),
	offsetof(struct X2SuccessfulOutcome__value, present),
	sizeof(((struct X2SuccessfulOutcome__value *)0)->present),
	asn_MAP_value_tag2el_4,
	25,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_value_4,
	25,	/* Elements count */
	&asn_SPC_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_X2SuccessfulOutcome_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProcedureCode,
		0,
		{ 0, &asn_PER_memb_procedureCode_constr_2,  memb_procedureCode_constraint_1 },
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Criticality,
		select_X2SuccessfulOutcome_criticality_type,
		{ 0, &asn_PER_memb_criticality_constr_3,  memb_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct X2SuccessfulOutcome, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_value_4,
		select_X2SuccessfulOutcome_value_type,
		{ 0, &asn_PER_memb_value_constr_4,  memb_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_X2SuccessfulOutcome_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_X2SuccessfulOutcome_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_X2SuccessfulOutcome_specs_1 = {
	sizeof(struct X2SuccessfulOutcome),
	offsetof(struct X2SuccessfulOutcome, _asn_ctx),
	asn_MAP_X2SuccessfulOutcome_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_X2SuccessfulOutcome = {
	"X2SuccessfulOutcome",
	"X2SuccessfulOutcome",
	&asn_OP_SEQUENCE,
	asn_DEF_X2SuccessfulOutcome_tags_1,
	sizeof(asn_DEF_X2SuccessfulOutcome_tags_1)
		/sizeof(asn_DEF_X2SuccessfulOutcome_tags_1[0]), /* 1 */
	asn_DEF_X2SuccessfulOutcome_tags_1,	/* Same as above */
	sizeof(asn_DEF_X2SuccessfulOutcome_tags_1)
		/sizeof(asn_DEF_X2SuccessfulOutcome_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2SuccessfulOutcome_1,
	3,	/* Elements count */
	&asn_SPC_X2SuccessfulOutcome_specs_1	/* Additional specs */
};

